InternTasks-2A
keremmimir/InternTasks-2A pull request #1
Opened 2024-07-19 08:38 UTC by keremmimir

2024-07-19 13:56 UTC, akndmr requested changes
Eline sağlık, bazı formatlama vs değişiklikler var

2024-07-19 13:56 UTC, akndmr commented on app/build.gradle.kts
> +    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
Bunu libs.toml a ekleyelim.

2024-07-19 13:56 UTC, akndmr commented on app/src/main/java/com/mobillium/interntasks2a/DetailActivity.kt
> +
1. Sınıfı formatlayalım ve gereksiz boşlukları silelim.
2. Optional : scope function
3. Hard-coded key'leri constant'a ekleyebiliriz.

2024-07-19 13:56 UTC, akndmr commented on app/src/main/java/com/mobillium/interntasks2a/DetailFragment.kt
> +    }
1. onCreate silinebilir
2. Hard-coded key'leri Object içinde constant'lara alabiliriz.
3. onDestroyView lifecycle'da binding...  **memory leak**

2024-07-19 13:56 UTC, akndmr commented on app/src/main/java/com/mobillium/interntasks2a/ListActivity.kt
> +}
1. Boşluklar, genel sınıf içi formatlama
2. Hard-coded key'ler constant'a (constant isimlendirme convention'ı)
3. `it`'i named hale getirebiliriz. `{ model ->`

2024-07-19 13:56 UTC, akndmr commented on app/src/main/java/com/mobillium/interntasks2a/ListAdapter.kt
> +}
1. holder içinde bir private bir function ile view'larımızın değerlerini set'leyebiliriz.
2. holder.binding tekrar ediyor
3. onclick isimlendirme camelCase
4. Formatlama yapalım

2024-07-19 13:56 UTC, akndmr commented on app/src/main/java/com/mobillium/interntasks2a/ListFragment.kt
> +}
1. Bundle'ı scope function ile setleyebiliriz. 
2. onClick dönüş parametresini named hale getirebiliriz. `model ->`
3. Key'leri constant'a alabiliriz.
4. DetailFragment değişken ismi PascalCase değil; camelCase

2024-07-19 13:56 UTC, akndmr commented on app/src/main/java/com/mobillium/interntasks2a/Model.kt
> +}
1. Formatlama
2. Trailing comma nedir? Ne zaman kullanılması tavsiye edilir?

2024-07-19 13:56 UTC, akndmr commented on app/src/main/java/com/mobillium/interntasks2a/Repository.kt
> +}
```
ArrayList<Model>().apply {
      add()
      add()
}
```

Formatlama

2024-07-19 13:56 UTC, akndmr commented on app/src/main/res/layout/activity_detail.xml
> +
Boşluğu silebiliriz

2024-07-19 13:56 UTC, akndmr commented on app/src/main/res/layout/activity_list.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
Üste bir satır boşluk

2024-07-19 13:56 UTC, akndmr commented on app/src/main/res/layout/activity_main.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
Üste bir satır boşluk

2024-07-19 13:56 UTC, akndmr commented on app/src/main/res/layout/fragment_list.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
Üste boşluk

2024-07-19 13:56 UTC, akndmr commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Kullanılmayan kodları silebiliriz

2024-07-25 11:22 UTC, aliosmanay requested changes

2024-07-25 11:22 UTC, aliosmanay commented on app/src/main/java/com/mobillium/interntasks2a/Model.kt
> +    var weather_degree : String,
camelCase yapabiliriz

2024-07-25 11:22 UTC, aliosmanay commented on app/src/main/java/com/mobillium/interntasks2a/Model.kt
> +    val degree_range : String,
camelCase yapabiliriz

2024-07-25 11:22 UTC, aliosmanay commented on app/src/main/res/drawable/button.xml
> +    <corners android:radius="15dp"/>
dimensiondan alabiliriz

2024-07-25 11:22 UTC, aliosmanay commented on app/src/main/res/layout/activity_detail.xml
> +        app:srcCompat="@drawable/ic_sunny" />
constaintDimensionRatio ve constraintWithPercent kullanarak boyutu daha responsive verebiliriz static degerler vermeden. Arastirabilirsin ek bilgi :)

2024-07-25 11:22 UTC, aliosmanay commented on app/src/main/res/layout/activity_detail.xml
> +        android:layout_width="wrap_content"
textlerde eger sag ve sol bagli ise matchConstrait yani 0dp kullanmak wrap yerine daha resposive bir yapi sunacaktir bize, suan sag sol margin de bulunmadigi icin tam ekranin genisliginde bir yazi gelirse ya da daha buyuk. Margin ve text elignment kullarak ayni gorunumu elde elebiliriz bu sayede ekrandan tasmalar ve bozukluklrdan  etkilenmeyiz.

2024-07-25 11:22 UTC, aliosmanay commented on app/src/main/res/layout/activity_navigation.xml
> +        android:layout_width="391dp"
bu buyuklukler pek olmamis gibi burada daha iyi bir cozum olabilir arastiralim.

2024-07-25 11:22 UTC, aliosmanay commented on app/src/main/AndroidManifest.xml
> +            android:exported="true">
bu da false olabilir sanki

2024-07-25 11:22 UTC, aliosmanay commented on app/src/main/java/com/mobillium/interntasks2a/ListActivity.kt
> +        binding.rv.adapter=adapter
bosluk yok  :) rv yerine daha anlamli isim olabilir sanki

2024-07-25 11:23 UTC, aliosmanay commented
@keremmimir  eline saglik 🚀

2024-11-27 19:58 UTC, merged